remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: "🎬 YouTube Movie Picker"
description: "A simple YouTube movie picker web app. Add movies by URL or search, filter by genre, and randomly pick what to watch."

github:
  repository_url: https://github.com/dannycab/ytmoviepicker
  repository_name: dannycab/ytmoviepicker
